# Generated by Django 4.0.4 on 2022-05-23 08:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 23, 8, 15, 27, 550468, tzinfo=utc)),
        ),
    ]
