# Generated by Django 4.0.4 on 2022-05-23 08:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_listing_current_bid_alter_listing_end_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 23, 8, 21, 8, 529471, tzinfo=utc)),
        ),
    ]
