# Generated by Django 4.0.4 on 2022-05-23 08:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_listing_image_alter_listing_start_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 23, 8, 34, 32, 246872, tzinfo=utc)),
        ),
    ]
