# Generated by Django 4.0.4 on 2022-05-23 09:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_listing_options_listing_owner_listing_winner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='datetime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 5, 23, 9, 9, 31, 567261, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='datetime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 5, 23, 9, 9, 31, 567261, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 23, 9, 9, 31, 566261, tzinfo=utc)),
        ),
    ]
