# Generated by Django 4.0.4 on 2022-05-25 01:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_alter_listing_options_remove_listing_current_bid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='winner',
        ),
        migrations.AlterField(
            model_name='bid',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 25, 1, 4, 50, 46696, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 25, 1, 4, 50, 46696, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 25, 1, 4, 50, 45694, tzinfo=utc)),
        ),
    ]
