# Generated by Django 4.0.4 on 2022-05-25 01:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_remove_listing_winner_alter_bid_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 25, 1, 5, 48, 812770, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 25, 1, 5, 48, 812770, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 25, 1, 5, 48, 811771, tzinfo=utc)),
        ),
    ]
