# Generated by Django 4.0.4 on 2022-05-26 02:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_alter_bid_datetime_alter_comment_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='condition',
            field=models.CharField(choices=[('New', 'Brand New'), ('Used once', 'Used once'), ('Used', 'Used')], default='New', max_length=9),
        ),
        migrations.AlterField(
            model_name='bid',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 26, 2, 28, 33, 354659, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 26, 2, 28, 33, 354659, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 26, 2, 28, 33, 353658, tzinfo=utc)),
        ),
    ]
